version: "3.9"

services:
  user:
    build:
      context: ./svc-user
    image: doranlocal/svc-user:local
    container_name: doran-user
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=doranchae_user
      - SPRING_DATASOURCE_PASSWORD=password
      

  community:
    build:
      context: ./svc-community
    image: doranlocal/svc-community:local
    container_name: doran-community
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/community_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=doranchae_user
      - SPRING_DATASOURCE_PASSWORD=password
      

  penpal:
    build:
      context: ./svc-penpal
    image: doranlocal/svc-penpal:local
    container_name: doran-penpal
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/penpal_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=doranchae_user
      - SPRING_DATASOURCE_PASSWORD=password
      

  welfare:
    build:
      context: ./svc-welfare
    image: doranlocal/svc-welfare:local
    container_name: doran-welfare
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/welfare_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=doranchae_user
      - SPRING_DATASOURCE_PASSWORD=password
      

  chat:
    build:
      context: ./svc-chat
    image: doranlocal/svc-chat:local
    container_name: doran-chat
    ports:
      - "8084:8084"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/chat_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=doranchae_user
      - SPRING_DATASOURCE_PASSWORD=password
      

  app:
    build:
      context: ./app
    image: doranlocal/app:local
    container_name: doran-app
    ports:
      - "3000:3000"
    depends_on:
      - user
      - community
      - penpal
      - welfare
      - chat
    
  db:
    image: mysql:8.0
    container_name: doran-mysql-db
    ports:
      - "3306:3306" # 로컬에서 DBeaver 등으로 접속하기 위해 포트 개방
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword # (임의 설정)
      # - MYSQL_USER=doranchae_user
      # - MYSQL_PASSWORD=password
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password